### PR TITLE
RUMM-3355 Rename Datadog to DatadogCore

### PR DESCRIPTION
**Pull request by maxep**
### What and why?

Rename `Datadog` to `DatadogCore`

### Review checklist
- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [x] Run unit tests
- [x] Run integration tests
- [x] Run smoke tests

### CODE REVIEW

**Review by maciejburda — APPROVED** [review]

**Comment by maxep** [comment]
This change was discussed during an iOS meeting but it conflicts with Android, cc @0xnm 

On Android, the [`Datadog` interface is part of the core package](https://github.com/DataDog/dd-sdk-android/blob/feature/sdkv2/dd-sdk-android-core/src/main/kotlin/com/datadog/android/Datadog.kt#L29), we must align on this crucial entrypoint.
I suggest to use `DatadogCore` for the library and `Datadog` for the api. If we agree on that, I will close this PR and make the necessary change for renaming the module.

LMKWYT @ncracker @maciejburda @ganeshnj

**Comment by ncreated** [comment]
> I suggest to use `DatadogCore` for the library and `Datadog` for the api.

Let's discuss it on V2 sync today.

Wrap up for the discussion:
* **V1** - suffers from https://github.com/apple/swift/issues/56573 problem:
```
pod install DatadogSDK

import Datadog

Datadog.initialize(...)
```

* **V2** - `suffix1` and `suffix2` **must be** distinct:
```
pod install DatadogSDK        # compatible with V1

import Datadog(suffix1)

Datadog(suffix2).initialize()
```

**Comment by maxep** [comment]
@ncreated What I suggest is to do:
```swift
pod install DatadogSDK

import DatadogCore

Datadog.initialize(...)
```

In case of CocoaPods, the `DatadogSDK` podspec will have the `DatadogCore` as a default subspec.
With SPM, users will use `.product(name: "Datadog", package: "DatadogCore")` as a dependency.

We won't suffer from https://github.com/apple/swift/issues/56573 and we would be aligned with Android, it also makes sense in term of semantic.
Yes, lets discuss that during sync 👍

**Comment by maxep** [comment]
Closing: We decided to go with `DatadogCore` as module and `Datadog` for the api.

**Comment by ncreated** [comment]
As discussed, we will go with:

> ```swift
> pod install DatadogSDK
> 
> import DatadogCore
> 
> Datadog.initialize(...)
> ```

**Pull request closed without merging**
