### PR TITLE
Update public API surface

### PR DESCRIPTION
**Pull request by 0xnm**
### What and why?

I wanted to see what we have in the public API, but it seems `api-surface-[swift,objc]` files were not updated for more than 1 year. So this PR does the necessary update.

`make api-surface` didn't work out of the box, because it is not supporting Apple Silicon. These are the changes I had to make to be able to run it, but since I am not quite sure that these changes are enough/best way to make it work, I won't add these changes to the PR and just show the diff:

```diff
diff --git a/Makefile b/Makefile
index 73645bc9..2f5b4fc4 100644
--- a/Makefile
+++ b/Makefile
@@ -122,9 +122,9 @@ sr-models-verify:
 api-surface:
                @cd tools/api-surface/ && swift build --configuration release
                @echo "Generating api-surface-swift"
-               ./tools/api-surface/.build/x86_64-apple-macosx/release/api-surface workspace --workspace-name Datadog.xcworkspace --scheme "Datadog iOS" --path . > api-surface-swift
+               ./tools/api-surface/.build/arm64-apple-macosx/release/api-surface workspace --workspace-name Datadog.xcworkspace --scheme "Datadog iOS" --path . > api-surface-swift
                @echo "Generating api-surface-objc"
-               ./tools/api-surface/.build/x86_64-apple-macosx/release/api-surface workspace --workspace-name Datadog.xcworkspace --scheme "DatadogObjc iOS" --path . > api-surface-objc
+               ./tools/api-surface/.build/arm64-apple-macosx/release/api-surface workspace --workspace-name Datadog.xcworkspace --scheme "DatadogObjc iOS" --path . > api-surface-objc

 # Generate Datadog monitors terraform definition for E2E tests:
 e2e-monitors-generate:
diff --git a/tools/api-surface/Package.swift b/tools/api-surface/Package.swift
index 85575ae3..2c86861b 100644
--- a/tools/api-surface/Package.swift
+++ b/tools/api-surface/Package.swift
@@ -1,14 +1,14 @@
-// swift-tools-version:5.2
+// swift-tools-version:5.7.1
 // The swift-tools-version declares the minimum version of Swift required to build this package.

 import PackageDescription

 let package = Package(
     name: "api-surface",
-    platforms: [.macOS(.v10_15)],
+    platforms: [.macOS(.v12)],
     dependencies: [
-        .package(url: "https://github.com/apple/swift-argument-parser", from: "0.2.0"),
-        .package(url: "https://github.com/jpsim/SourceKitten.git", .exact("0.29.0")),
+        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.2.0"),
+        .package(url: "https://github.com/jpsim/SourceKitten.git", .exact("0.33.1")),
     ],
     targets: [
         .target(
```

### Review checklist
- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [ ] Run unit tests
- [ ] Run integration tests
- [ ] Run smoke tests

### CODE REVIEW

**Review by maciejburda — APPROVED** [review]
LGTM - I wonder if we should maybe have two makefiles for both architectures or maybe discover they architecture in the script.

**Comment by ncreated** [comment]
> LGTM - I wonder if we should maybe have two makefiles for both architectures or maybe discover they architecture in the script.

The second option looks best - the path to executable can be read with `swift build --show-bin-path` to avoid hardcoding it in the `Makefile` 👍.

**Review by ncreated — APPROVED** [review]
Looks good, thank you @0xnm 👍. We can fix the `make` command either here or through separate JIRA (the diff looks fine except we should avoid hardcoding the path).

**Comment by 0xnm** [comment]
I've created a separate ticket RUMM-2833 to support Apple Silicon for the API surface generation.

**Pull request merged**
