### PR TITLE
Extend app launch handler to macCatalyst and visionOS

### PR DESCRIPTION
**Pull request by Hengyu**
### What and why?

We can have app launch info on macCatalyst platform and visionOS platform

### How?

Use #macro to gate platforms

### Review checklist
- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [ ] Run unit tests for Core, RUM, Trace, Logs, CR and WVT
- [ ] Run unit tests for Session Replay
- [ ] Run integration tests
- [ ] Run smoke tests
- [ ] Run tests for `tools/`

### CODE REVIEW

**Comment by ncreated** [comment]
Thanks @Hengyu 👋. We will take it over from here and merge to internal branch for CI and QA.

**Comment by Hengyu** [comment]
Thanks a lot @ncreated

**Comment by MaelNamNam** [comment]
Hi @Hengyu 👋 Thanks fro your contribution! We just released this in version [2.17.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.17.0)

**Comment by johnHackworth** [comment]
Hey @Hengyu 👋 Just a follow-up — building on your contribution, full official visionOS support (including RUM, Crash Reporting, Profiling, and Web View Tracking) has now shipped in **[v3.10.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/3.10.0)**. Thanks again for helping lay the groundwork! 🙏

**Comment by Hengyu** [comment]
Thanks @johnHackworth

**Pull request merged**
