### PR TITLE
RUM-3574 perf: Start sending batches immediately after feature is initialized

### PR DESCRIPTION
**Pull request by ncreated**
### What and why?

📦⏱️ This PR removes the initial delay for sending batches. Now, first upload will be triggered soon after feature is initialized.

The motivation is to maximise a chance of sending data if application is impacted by early crash.
Related to https://github.com/DataDog/dd-sdk-flutter/issues/573

### How?

Removing initial delay from `DataUploadWorker`.

Before:
```
----[I]------------[U1]----------------[U2]-->
     ^ SDK init
                    ^ initial upload
                                         ^ next upload
```

Now:
```
----[I][U1]----------------[U2]-->
     ^ SDK init
        ^ initial upload
                             ^ next upload
```

### Review checklist
- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference
- [x] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [ ] Run unit tests for Core, RUM, Trace, Logs, CR and WVT
- [ ] Run unit tests for Session Replay
- [ ] Run integration tests
- [ ] Run smoke tests
- [ ] Run tests for `tools/`

### CODE REVIEW

**Comment by ncreated** [comment]
Back to draft as the CI got flaky on BG tasks tests in `DataUploadWorker`.

**Review by maciejburda — APPROVED** [review]

**Comment by ganeshnj** [comment]
I'm curious about the impact when a notification triggers app load and we will send anything pending all at the same time.

**Comment by ncreated** [comment]
> I'm curious about the impact when a notification triggers app load and we will send anything pending all at the same time.

As we discussed, we only change the delay of initial upload, so practically there won't be a change to the load spike in this scenario - it will be only shifted earlier in time.

**Review by ganeshnj — APPROVED** [review]

**Review by maxep — APPROVED** [review]
👍

**Pull request merged**
