### PR TITLE
RUM-3222 Move Session Replay obj-c interfaces directly to the target

### PR DESCRIPTION
**Pull request by maciejburda**
### What and why?

Moves obj-c interfaces of Session Replay as described in the [RFC](https://datadoghq.atlassian.net/wiki/spaces/RUMP/pages/3157787243/RFC+-+Modular+Objective-C+Interface)

### Review checklist
- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [ ] Run unit tests for Core, RUM, Trace, Logs, CR and WVT
- [ ] Run unit tests for Session Replay
- [ ] Run integration tests
- [ ] Run smoke tests
- [ ] Run tests for `tools/`

### CODE REVIEW

**Review by ncreated — COMMENTED** [review]
💡 Moving the SR API from `DatadogObjc` to `DatadogSessionReplay` is a breaking-change, no? What is the rationale and mitigation?

**Comment by maciejburda** [comment]
@ncreated 
Truth be told, ticket originated because we missed the fact we already support obj-c in the wrapper package.

We discussed this with @maxep and it should work without a change on the customer side.

It's following the v2 idea of moving all the obj-c api directly to targets and deprecating the obj-c wrapper.

**Review by ncreated — DISMISSED** [review]

**Comment by maciejburda** [comment]
Getting this in snapshot tests:

`target at '~/dd-sdk-ios/DatadogSessionReplay/Tests' contains mixed language source files; feature not supported`

Will try to resolve later. But sounds like it may require slightly different approach.

**Review by ncreated — APPROVED** [review]
🎯 nice!

**Pull request merged**
