### PR TITLE
Make DDSpan final class

### PR DESCRIPTION
**Pull request by muukii**
### What and why?

It won't speed up so much as using this class over OTSpan protocol in most cases.
Anyway, making this class `final` gets maintainability, and improves performance of using static-dispatch potentially.

### How?

A brief description of implementation details of this PR.

### Review checklist
- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [ ] Run unit tests
- [ ] Run integration tests
- [ ] Run smoke tests

### CODE REVIEW

**Review by maxep — APPROVED** [review]
Thanks 🙏

**Comment by maxep** [comment]
@muukii 👋  Thank you for your contribution!
Our organisation requires commit with verified signature.. Would you be able to push signed commits?

**Comment by maciejburda** [comment]
@muukii Unfortunately I don't think organisation setup allows us to do that.

I think it will be easier if you could setup GPG signing:
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

And resign the commit:
```git rebase --exec 'git commit --amend --no-edit -n -S' -i develop```

**Comment by muukii** [comment]
@maciejburda yup, you're right. I'm done!

**Pull request merged**
