### PR TITLE
Merge `feature/v2` to `develop`

### PR DESCRIPTION
**Pull request by maxep**
### What and why?

Merge `feature/v2` to `develop`

### How?

The following conflicts were resolved during the merge. Authors of the following PRs are invited to review their respective changes.

- #1347 @maciejburda 
- #1328 @ganeshnj 
- #1354 @ganeshnj 

Additionally, the E2E Tests have been migrated, see 16f13adfe60be6f455ca4222b430e575b756ead7

### Review checklist
- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [x] Run unit tests
- [x] Run integration tests
- [x] Run smoke tests

### CODE REVIEW

**Comment by maxep** [comment]
image

**Review by maciejburda — APPROVED** [review]

**Review by ganeshnj — APPROVED** [review]

**Review by buraizu — APPROVED** [review]
Not sure a docs team review is needed here, but LGTM

**Review by ncreated — CHANGES_REQUESTED** [review]
🏋️‍♀️ Looks good, except that we also need to fix E2E tests build by updating the API to 2.0.0 (it uses V1 on `feature/v2`):

Screenshot 2023-07-11 at 08 44 49

Otherwise, all monitors we define in MI org will fail in next nightly build. The E2E tests are safe to try in local, as they send data to different env:

https://github.com/DataDog/dd-sdk-ios/blob/develop/Datadog/E2E/E2EConfig.swift#L48-L53

**Comment by maxep** [comment]
@ncreated! Indeed, I was planning on doing it after the merge but better to do it now 👍 
E2E Tests are now migrated and [data is coming through](https://mobile-integration.datadoghq.com/rum/sessions?query=%40type%3Asession%20%40application.id%3Af004d05f-3d42-4441-90ab-04d020bebe94%20env%3Adebug&cols=&from_ts=1689026400000&to_ts=1689069000000&live=false).

I have also updated the api-surface.

**Review by ncreated — APPROVED** [review]
🚀

**Pull request merged**
