### PR TITLE
RUMM-602 Shopist: Cart added

### PR DESCRIPTION
**Pull request by buranmert**
### What and why?

We need Shopist app to generate RUM data for demos

### How?

We added Cart page to add items and then check them out

### Visuals

detail
cart-iOS

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

### CODE REVIEW

**Comment by nachoBonafonte** [comment]
Just a small UI thing:
Screenshot 2020-08-05 at 13 00 04

**Comment by buranmert** [comment]
@nachoBonafonte you mean the formatting issue or `tableView.allowsSelection` issue?
i just pushed `allowsSelection = false` ✅

**Comment by nachoBonafonte** [comment]
I was thinking on the formatting, but yes, much better without selection

**Comment by buranmert** [comment]
@nachoBonafonte formatting fixed ✅ 
cart-v2

**Pull request merged**
