### PR TITLE
fix: Always assume device is online on Apple Watch

### PR DESCRIPTION
**Pull request by maxep**
### What and why?

Skip `networkReachability` check for uploading on watchOS.

ext contribution: #2005

### Review checklist
- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [ ] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### CODE REVIEW

**Review by ncreated — COMMENTED** [review]
Question/ What will happen to the "failed" connections and how will they impact the next upload delay? In case of "offline" is the failure immediate or comes with certain delay?

**Comment by maxep** [comment]
@ncreated Good question, we might fall under [this](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogCore/Sources/Core/Upload/DataUploadStatus.swift#L53) and never retry the request..
We should test this, preferably on a physical watch. @mariedm would you be able to test this?

**Comment by mariedm** [comment]
> @ncreated Good question, we might fall under [this](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogCore/Sources/Core/Upload/DataUploadStatus.swift#L53) and never retry the request.. We should test this, preferably on a physical watch. @mariedm would you be able to test this?

Yes, I will!

**Comment by mariedm** [comment]
I tested on an Apple Watch Series 7 running watchOS 10.6.1. I can confirm that the network is reachable on the simulator but not on my device.

When bypassing the network reachability check on watchOS, [uploadStatus.needsRetry](https://github.com/DataDog/dd-sdk-ios/blob/7a57ec74a7150e761d700a1471cb45b0a9605930/DatadogCore/Sources/Core/Upload/DataUploadWorker.swift#L123) returns `true`. After restoring the internet connection, uploads resume as expected, so this approach appears safe.

I found out about the [Watch Connectivity](https://developer.apple.com/documentation/watchconnectivity) framework which can determine if the paired iPhone is reachable. This might be useful in the future in case we want to make this solution more robust.

**Comment by maxep** [comment]
Thanks for testing @mariedm 🙏  It is good to merge then, WDYT @ncreated ?

**Review by ncreated — APPROVED** [review]

**Comment by ncreated** [comment]
> Thanks for testing @mariedm 🙏 It is good to merge then, WDYT @ncreated ?

Yes 👌. Thanks for assurance @mariedm 💪

**Pull request merged**
