### PR TITLE
RUMM-2938 Move DatadogSessionReplay Sources and Tests

### PR DESCRIPTION
**Pull request by maxep**
### What and why?

Move sources and tests to comply with future project structure and facilitate migration in v2

This needs to be done early so we can keep the v2 branch up to date with `develop`.
@ncreated and @maciejburda make sure to rebase your current branches after this is merged to `develop`.

### Review checklist
- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference
- [ ] Add CHANGELOG entry for user facing changes

### Custom CI job configuration (optional)
- [x] Run unit tests
- [x] Run integration tests
- [ ] Run smoke tests

### CODE REVIEW

**Review by maciejburda — COMMENTED** [review]
I trust you on this one, but isn't that the case already?
Screenshot 2023-02-02 at 16 24 26

Also - would be great to wait for that one before we merge:
https://github.com/DataDog/dd-sdk-ios/pull/1144

I hope to merge it by the end of the week.

**Comment by maxep** [comment]
> I trust you on this one, but isn't that the case already?
It's currently `DatadogSessionReplay/Sources/DatadogSessionReplay/`, I'm removing the last `DatadogSessionReplay` folder.

Totally, lets wait for https://github.com/DataDog/dd-sdk-ios/pull/1144 👍

**Review by ncreated — APPROVED** [review]
Looks good and good to merge after #1144 👍.

Alternatively, to avoid waiting or struggling with git conflicts, we could use two symbolic links (`DDSR/Sources/DDSR` → `DDSR/Sources`, `DDSR/Tests/DDSRTests` → `DDSR/Tests`) for the period o migration and just move all files at once during a short code freeze at the end.

**Comment by maciejburda** [comment]
Blocking PR merged 🟢

**Pull request merged**
