### PR TITLE
RUMM-1744 Update release tool to conditionally validate `Kronos.xcframework`

### PR DESCRIPTION
**Pull request by ncreated**
### What and why?

📦 This PR updates our release automation so it can conditionally include/exclude certain `XCFrameworks` from GitHub release asset validation (`.*zip`). This is required as starting from `1.9.0` SDK will no longer depend on `Kronos.xcframework` (#701), but when (re)building historical tags, we want it to be included.

### How?

I extracted the code for validating each `XCFramework` and used OCP to make it configurable for a certain range of `Version`. 

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

### CODE REVIEW

**Review by buranmert — APPROVED** [review]
i'm not sure if this is the simplest solution but as long as it works it's fine for me

**Review by maxep — APPROVED** [review]
LGTM!

**Comment by ncreated** [comment]
> i'm not sure if this is the simplest solution but as long as it works it's fine for me

@buranmert do you see anything in particular that we could simplify? My goal was to have separate validation for each `XCFramework` and this way we can assert more critical aspects: swift compatibility, architecture slices and dSYMs presence. Given that soon we will produce more slices (V2, next platforms), I think this approach should be reliable and easy to scale.

**Comment by buranmert** [comment]
it's just seeing `+468 −37` made me wonder if that was the simplest solution.
i mean as far as i can see we do basically
```
if version < SOME_VERSION
  kronos_should_not_exist()
else
  kronos_should_exist_with_its_content()
```

**Comment by ncreated** [comment]
> it's just seeing `+468 −37` made me wonder if that was the simplest solution. i mean as far as i can see we do basically
> 
> ```
> if version < SOME_VERSION
>   kronos_should_not_exist()
> else
>   kronos_should_exist_with_its_content()
> ```

It would need another `if/else` for crash reporting (`1.7.0+`) and several more for next platforms (tvOS / watchOS) + eventual modules in V2, ending up with `if/else` pyramid. Given no integration tests for this tool, introducing complex and not tested control flows sounds error prone which is where basic and declarative OCP should help.

**Pull request merged**
