### PR TITLE
RUMM-1900/1904 Update RUM Schema

### PR DESCRIPTION
**Pull request by fuzzybinary**
Adds support for flutter error source (RUMM-1900)

### How?

Ran the Schema generator

### Review checklist

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

### CODE REVIEW

**Comment by buranmert** [comment]
we can wait for https://github.com/DataDog/rum-events-format/pull/53 a little bit and update both at once

**Comment by fuzzybinary** [comment]
@buranmert 👍 I'm okay waiting. I'll switch this over to a draft PR and if you want you can build off it once DataDog/rum-events-format#53 goes in.

**Comment by fuzzybinary** [comment]
👍 LGTM -- we'll need one other approver though

**Review by ncreated — APPROVED** [review]
👌

**Pull request merged**
