### PR TITLE
RUMM-432 Clean up the way `OpenTracing.framework` is linked

### PR DESCRIPTION
**Pull request by ncreated**
### What and why?

🔗 This PR cleans up the way `Datadog.framework` and `OpenTracing.framework` are provided to the customer's app. 

### How?

`Datadog.framework` does no longer embed the `OpenTracing.framework`. Instead, it links it:

Screenshot 2020-05-12 at 15 01 54

Screenshot 2020-05-12 at 15 04 14

Screenshot 2020-05-12 at 15 04 24

I also update other Xcode projects in the repository:

#### Datadog.xcodeproj
* `DatadogTests` → _Link Binary With Libraries_ = `DD.framework`, no `OT.framework`.
* `DatadogBenchmarkTests` → _LBWL_ = `DD.framework`, no `OT.framework`.
* `DatadogIntegrationTests` → _LBWL_ = only `HTTPServerMock`.
* `Example` → _Frameworks, Libraries and Embedded Content_ = `DD.framework`, + `OT.framework`.

#### Shopist.xcodeproj
* `Shopist` → _Frameworks, Libraries and Embedded Content_ = `DD.framework`, + `OT.framework`.
* `ShopistUITests` → nothing.

#### CPProject.xcodeproj
* Added `import OpenTracing`, to make sure this links and runs.
* No changes to targets setup.

#### CTProject.xcodeproj
* Added `import OpenTracing`, to make sure this links and runs.
* The Carthage `copy-frameworks` script takes: `DD.framework` and `OT.framework`.
* _Frameworks, Libraries and Embedded Content_ = `DD.framework`, + `OT.framework`.

#### SPMProject.xcodeproj
* Added `import OpenTracing`, to make sure this links and runs.
* No changes to targets setup.
* _Frameworks, Libraries and Embedded Content_ = `DD.framework`.

💡 In `SPMProject` the `OpenTracing` dependency pops-up nowhere, but in the project navigator. This still makes `import OpenTracing` possible. It's probably because `Datadog` is compiled as static library and its dependencies are automatically transitive 🤔.

Screenshot 2020-05-12 at 15 19 47

### 🎁 Bonus things

I also pushed [this commit to `DataDog/opentracing-swift`](https://github.com/DataDog/opentracing-swift/commit/109c0635deb742521edfebcfc9ec055f30b5b668) so we can improve the public OT api:
```diff
- tracer.startSpan(operationName: "root span", childOf: nil)
+ tracer.startSpan(operationName: "root span")
```

### Review checklist

- [x] Feature or bugfix MUST have appropriate tests (unit, integration)
- [x] Make sure each commit and the PR mention the Issue number or JIRA reference

### CODE REVIEW

**Comment by buranmert** [comment]
`SPM` issue sounds interesting 🤔 
we've recently changed SDK's type to `dynamic`, does it still link it to `SPMExample` statically?
can we make sure `OT.framework` exists withing `SPMExample.app` product?

**Comment by ncreated** [comment]
> we've recently changed SDK's type to dynamic, does it still link it to SPMExample statically?

Indeed, it's weird But yes, it seems to link statically, although the `Package.swift` in resolved dependency clearly states `.dynamic`.

> can we make sure `OT.framework` exists withing `SPMExample.app` product?

It's not there:

Screenshot 2020-05-12 at 18 32 38

But the `OpenTracing` interface visibility seems to come from this `OT.swiftmodule`:

Screenshot 2020-05-12 at 18 37 53

**Comment by buranmert** [comment]
It seems like SPM is merging `OT` into `Datadog`
i assume if we look into `Datadog` binary we will see symbols from `OT` as well
before i approve, can you please check if they are in the binary please? 🙏 

if so; although that's not what we want exactly, it should be fine for us ✅

**Comment by ncreated** [comment]
@buranmert I compared these two:
* `CTProject.app/Frameworks/Datadog.framework/Datadog` 
* `SPMProject.app/Frameworks/Datadog.framework/Datadog` 

First contains only 9 symbols:
```
❯ objdump -t /.../CTProject.app/Frameworks/Datadog.framework/Datadog | grep OpenTracing | grep -v Datadog        
00000000000232b0 lw    F __TEXT,__text _$s11OpenTracing9ReferenceVWOc
00000000000232e0 lw    F __TEXT,__text _$s11OpenTracing9ReferenceVWOh
0000000000000000         *UND* _$s11OpenTracing11SpanContextMp
0000000000000000         *UND* _$s11OpenTracing12FormatWriterMp
0000000000000000         *UND* _$s11OpenTracing13TextMapWriterMp
0000000000000000         *UND* _$s11OpenTracing17HTTPHeadersWriterMp
0000000000000000         *UND* _$s11OpenTracing18CustomFormatWriterMp
0000000000000000         *UND* _$s11OpenTracing4SpanMp
0000000000000000         *UND* _$s11OpenTracing6TracerMp
```

Second contains 292 symbols in total, heading with:
```
❯ objdump -t /.../SPMProject.app/Frameworks/Datadog.framework/Datadog | grep OpenTracing | grep -v Datadog       
000000000002b130 lw    F __TEXT,__text _$sSay11OpenTracing9ReferenceVGSayxGSTsWl
000000000002b180 lw    F __TEXT,__text _$sSay11OpenTracing9ReferenceVGMa
000000000002b210 lw    F __TEXT,__text _$sSay11OpenTracing9ReferenceVGWOh
000000000002b310 lw    F __TEXT,__text _$s11OpenTracing11SpanContext_pWOc
000000000006b640 lw    F __TEXT,__text _$s11OpenTracing6Tracer_pWOc
000000000006b770 lw    F __TEXT,__text _$s11OpenTracing6Tracer_pWOb
000000000006b7e0 l     F __TEXT,__text _$s11OpenTracing6GlobalV12sharedTracerAA0E0_pvMZ.resume.0
000000000006b820 l     F __TEXT,__text _$s11OpenTracing11NoopGlobals33_B686EC6F04612823A1045A176566C0CBLLV6tracerAA0C6TracerVvau
000000000006b870 l     F __TEXT,__text _$s11OpenTracing11NoopGlobals33_B686EC6F04612823A1045A176566C0CBLLV4spanAA0C4SpanVvau
000000000006b8c0 l     F __TEXT,__text _$s11OpenTracing11NoopGlobals33_B686EC6F04612823A1045A176566C0CBLLV7contextAA0C11SpanContextVvau
...
```
Which looks like dynamic vs static linking.

Also no reference in:
```
❯ otool -L /.../SPMProject.app/Frameworks/Datadog.framework/Datadog | grep OpenTracing
```
vs an `@rpath` reference in:
```
❯ otool -L /.../CTProject.app/Frameworks/Datadog.framework/Datadog | grep OpenTracing   	
@rpath/OpenTracing.framework/OpenTracing (compatibility version 1.0.0, current version 1.0.0)
```
All correct IMO 👌.

**Comment by ncreated** [comment]
👍 I will merge after #107, this way it should be easier with git conflicts.

**Pull request merged**
